### PR TITLE
Fix #26

### LINKED ISSUE #26: Distinct Instances of Date Range picker share same config
I have a problem when using the date range picker in two different combination, once with single date and once with date range. Both are in two different pages (even popups). When using any one individually it works, however. When first using the single date picker and then navigating to a page with the date range picker, only a single date drop down is shown. Somehow there seems to be a global state that is not reset.

Happens on all browsers and latest angular-daterangepicker version.

Any idea where to start looking for this? as we use the component directly I do not see how this can be coming from any configuration we do, looks like something that is not reset from a global daterangepicker setting?

### PR DESCRIPTION
**Pull request by tcooc**
Fix #26.
Use clean config for each daterangepicker.
Fix not cleaning up after itself when scope is destroyed.

The original code did not clean up after itself when switching views, and also extended a global variable which is then applied to all daterangepickers. This PR fixes that.

### CODE REVIEW

**Comment by elm-** [comment]
@tcooc thanks for the fix, it definitly makes sense from a code perspective, however for me it does not fix #26, I still have the same issue. After the single view has been used, it still shows a single view for the next usage that is configured as range. I also get an exception in some cases that the remove is called on an undefined element, I haven't been able to figure out when and when not though, could be related to being in a modal.
I double checked the initialization, my problem seems to be related to the case that customOpts is actually undefined after it is parsed ...

**Comment by tcooc** [comment]
@elm- Sorry to hear that. I had 2 separate daterangepickers on 2 different pages, one being a single daterangepicker, and this fixed it for me. It would be helpful if you could provide an example, since my use case sounds the same as yours.

(Also, just in case, did you update to this latest change? You'll have to do `bower instal git@github.com:fragaria/angular-daterangepicker.git#ce00c1047f2abd504b3b1995e33bf95eeba9a81a` since these changes haven't been released yet)

**Comment by elm-** [comment]
@tcooc I did not use bower, I just replaced the JavaScript in the downloaded component and verified that it was compiled into my vendor scripts, should do the trick.

I have my date pickers placed in modals, that might potentially be an issue as I know Angular-UI  has some issues with scoping in that case. I'll try to reduce it to a simple case (it is part of a 10k lines coffeescript app, there are probably other factors involved).

What I observed so far is that the customOpts variable evaluates to undefined and not the options array. That could be a reason.

**Comment by krtek** [comment]
Hello, 
I merged your PR and released new version with it. @elm- you can try the bower version now. 

Thank you!

**Comment by elm-** [comment]
@krtek also happening with 0.1.11 from bower, but I Just noticed that the instance is actually not cleaned from the body stack. every time I re-open a modal with the date range picker it is added to the HTML body. I'll investigate there.

**Comment by elm-** [comment]
Ok, I meant 0.1.12 not 0.1.11. The problem is that $destroy fails with, I think this is related to the modal where the directive is used in.

```
TypeError: Cannot read property 'remove' of undefined
    at http://localhost:9000/assets/js/vendor.js:58440:44
    at Scope.$broadcast (http://localhost:9000/assets/js/vendor.js:23669:28)
    at Scope.$destroy (http://localhost:9000/assets/js/vendor.js:23327:14)
    at http://localhost:9000/assets/js/vendor.js:60409:34
    at afterAnimating (http://localhost:9000/assets/js/vendor.js:60455:13)
    at HTMLDivElement.<anonymous> (http://localhost:9000/assets/js/vendor.js:60439:13)
    at HTMLDivElement.jQuery.event.dispatch (http://localhost:9000/assets/js/vendor.js:4641:9)
    at HTMLDivElement.elemData.handle (http://localhost:9000/assets/js/vendor.js:4309:46) 
```

**Comment by tcooc** [comment]
@elm- Did this fix the issue with the 2 daterangepickers having the same config? This change should have fixed that.

I understand that this doesn't cleanup properly when using modals, but everything should still work. I'm working on a fix for cleanup issue.

**Comment by elm-** [comment]
@tcooc yes, it fixes it. I had some time to look at it today and noticed that the options passed to the date range picker are actually the wrong ones, so there was also a bug on our side. 

The way this happened: We have a global default template for the date range picker which we clone and customize for the individual usage. At one usage extend instead of copy was used, which resulted in the template being modified and therefore being applied to all other parts.

Offtopic: We started making all our constants and templates actual constants by providing them through functions, so there is no way to modify their global state, this one was not covered yet. I'm really looking forward to freeze / immutability support on JavaScript, maybe then I can get warmer with the whole frontend stuff =)

Thanks for your help, really appreciate it!

**Pull request merged**
