### PR TITLE
Fix input showing "invalid date" when startDate/endDate is null

### PR DESCRIPTION
**Pull request by shanesmith**

### CODE REVIEW

**Comment by Wlada** [comment]
+1

**Comment by Meabed** [comment]
+!

**Comment by brazentongue** [comment]
+1

**Comment by Wlada** [comment]
After @shanesmith update everything works fine.

Can someone consider to merge this updates ? I tested on single date picker. Will try to test also on date range.

Thanks @shanesmith !

**Comment by raygerrard** [comment]
Any idea when this will be getting merged in? @krtek

**Comment by krtek** [comment]
Merged, thank you!

**Comment by shanesmith** [comment]
Thanks for merging!

**Comment by raygerrard** [comment]
Thanks

**Comment by asabirov** [comment]
Input doesn't update after date picked (singleDatePicker: true). I'm not sure, I think it's because of removing this https://github.com/fragaria/angular-daterangepicker/commit/0a31db8e3953b9666eed839cc2754ce829f46fd3#diff-efa1315bffa7dd725a0f8646ffd35803L70

**Comment by shanesmith** [comment]
@asabirov thanks for letting me know, my fault, fixed in #133

**Pull request merged**
