### PR TITLE
Fix all the things

### PR DESCRIPTION
**Pull request by phazei**
This PR incorporates many of the issues from the other PR's in addition to many other fixes and improvements.
It's updated to work with daterangepicker 3.0 (most of that didn't really change, just the removal of the BS3 dependency)

- Listening of the model to update the picker now works properly and doesn't require an entirely new object so just the moment item can be updated.
- Validation work better with single and range picker.  The min/max date can just be included with the daterangepicker options instead of having to be attributes.
- Numerous bugs with daterangepicker have been fixed as well.
- Can now cancel out of selection if clicking outside of datepicker without applying.
- Can now apply additional classes to the picker popup (for example to add an inline class or custom styling class).
- Daterangepicker data object can now be sent back to a variable via a "picker=obj" attribute

README.md has been updated with new updations.  example.html has been updated to work and include new options and better formatting.

### CODE REVIEW

**Comment by phazei** [comment]
Also update version to 0.3.0

**Comment by krtek** [comment]
Looks good to me 👍 
Thanks for the hard work. Do I have a green light to merge this? 

Lukas

PS: You should add yourself to `CONTRIBUTORS.md` and the `authors` tag in `package.json` 😀

**Comment by phazei** [comment]
Did as you suggested.  PR is GTG.

**Comment by krtek** [comment]
Thanks a lot - merged and released.

**Pull request merged**
