### PR TITLE
solved multiple event handlers binding problem

### PR DESCRIPTION
**Pull request by wubin1989**
commit

### CODE REVIEW

**Comment by devillex** [comment]
Hi. Can someone please have a look at this pull request? I am having the exact same problem with a combination of apply.* and cancel.* event handlers.

**Comment by krtek** [comment]
Hello, 
would you mind to write this into [Coffeescript source](https://github.com/fragaria/angular-daterangepicker/blob/master/coffee/angular-daterangepicker.coffee) so I can merge it?

Thanks, 
Lukas

**Comment by wubin1989** [comment]
Hi Lukas,

I am not so familiar with Coffeescript, but I tried to write the code into the file.
If it can not run properly, please advise me.

Best Regards,
Will

**Comment by devillex** [comment]
Hi @krtek. Please see #111 with @wubin1989 's changes in CoffeeScript.

**Comment by krtek** [comment]
Closing as was solved by #111. Thank you!

**Pull request closed without merging**
